/**
 * WASM Initialization
 *
 * Handles initialization of the WASM module, localization, and WASM-powered components
 * This is separate from the main plane_builder.ts to allow gradual migration
 */

import { localization } from './wasm/localization';
import { AircraftBridge } from './wasm/aircraft_bridge';
import { LanguageSelector } from './wasm/components/language_selector';
import { EraUI } from './wasm/components/era_ui';

// Type for the WASM module (will be generated by wasm-pack)
// For now, we'll use 'any' until WASM is built
type WasmModule = any;

export class WasmApplication {
    private bridge: AircraftBridge | null = null;
    private languageSelector: LanguageSelector | null = null;
    private eraUI: EraUI | null = null;
    private initialized: boolean = false;

    /**
     * Initialize the WASM application
     */
    async initialize(): Promise<void> {
        try {
            console.log('[WasmApp] Starting WASM initialization...');

            // Dynamically import the WASM module
            // This will be generated by wasm-pack: Test/pkg/flyingcircuswasm
            const wasmModule = await this.loadWasmModule();

            if (!wasmModule) {
                console.warn('[WasmApp] WASM module not available, using fallback mode');
                return;
            }

            // Initialize localization with WASM backend
            localization.initializeWasm(wasmModule.Localization);
            console.log('[WasmApp] Localization initialized');

            // Set locale from URL parameter or localStorage
            const urlParams = new URLSearchParams(window.location.search);
            const langParam = urlParams.get('lang');
            if (langParam) {
                localization.setLocale(langParam);
                console.log(`[WasmApp] Locale set from URL: ${langParam}`);
            }

            // Create aircraft bridge
            this.bridge = new AircraftBridge();
            await this.bridge.initialize(
                wasmModule.default,
                wasmModule.AircraftWasm
            );
            console.log('[WasmApp] Aircraft bridge initialized');

            // Check for aircraft data in URL (for loading shared aircraft)
            const jsonParam = urlParams.get('json');
            if (jsonParam && this.bridge) {
                try {
                    const loadedBridge = await AircraftBridge.deserializeFromLZString(
                        jsonParam,
                        wasmModule.default,
                        wasmModule.AircraftWasm
                    );
                    this.bridge = loadedBridge;
                    console.log('[WasmApp] Loaded aircraft from URL');
                } catch (e) {
                    console.error('[WasmApp] Failed to load aircraft from URL:', e);
                }
            }

            // Create language selector
            this.languageSelector = new LanguageSelector('language_selector_container');
            console.log('[WasmApp] Language selector created');

            // Create Era UI component
            this.eraUI = new EraUI(this.bridge, 'Era', () => {
                this.onStatsUpdate();
            });
            console.log('[WasmApp] Era UI created');

            this.initialized = true;
            console.log('[WasmApp] Initialization complete!');
        } catch (error) {
            console.error('[WasmApp] Failed to initialize WASM:', error);
            console.log('[WasmApp] Continuing with TypeScript-only mode');
        }
    }

    /**
     * Load the WASM module
     * Returns null if WASM is not available (not yet built)
     */
    private async loadWasmModule(): Promise<WasmModule | null> {
        try {
            // Try to import the WASM module
            const wasmModule = await import('../pkg/flyingcircuswasm');
            return wasmModule;
        } catch (e) {
            console.warn('[WasmApp] WASM module not found (not yet built):', e);
            return null;
        }
    }

    /**
     * Called when stats need to be updated
     */
    private onStatsUpdate(): void {
        if (!this.bridge) return;

        // Recalculate stats in Rust
        this.bridge.calculateStats();

        // Get derived stats
        const derivedStats = this.bridge.getDerivedStats();
        console.log('[WasmApp] Stats updated:', derivedStats);

        // TODO: Update stats display in UI
        // For now, just log to console
    }

    /**
     * Check if WASM is initialized
     */
    isInitialized(): boolean {
        return this.initialized;
    }

    /**
     * Get the aircraft bridge (if initialized)
     */
    getBridge(): AircraftBridge | null {
        return this.bridge;
    }
}

/**
 * Global WASM application instance
 */
export const wasmApp = new WasmApplication();
