/**
 * WASM Initialization
 *
 * Handles initialization of the WASM module, localization, and WASM-powered components
 * This is separate from the main plane_builder.ts to allow gradual migration
 */

import { localization } from './wasm/localization';
import { AircraftBridge } from './wasm/aircraft_bridge';
import { LanguageSelector } from './wasm/components/language_selector';
import { EraUI } from './wasm/components/era_ui';
import { CockpitsUI } from './wasm/components/cockpits_ui';
import { PropellerUI } from './wasm/components/propeller_ui';
import { PassengersUI } from './wasm/components/passengers_ui';
import { LoadUI } from './wasm/components/load_ui';
import { AccessoriesUI } from './wasm/components/accessories_ui';
import { ControlSurfacesUI } from './wasm/components/control_surfaces_ui';
import { LandingGearUI } from './wasm/components/landing_gear_ui';
import { OptimizationUI } from './wasm/components/optimization_ui';
import { ReinforcementsUI } from './wasm/components/reinforcements_ui';
import { StabilizersUI } from './wasm/components/stabilizers_ui';

// Type for the WASM module (will be generated by wasm-pack)
// For now, we'll use 'any' until WASM is built
type WasmModule = any;

export class WasmApplication {
    private bridge: AircraftBridge | null = null;
    private languageSelector: LanguageSelector | null = null;
    private eraUI: EraUI | null = null;
    private cockpitsUI: CockpitsUI | null = null;
    private propellerUI: PropellerUI | null = null;
    private passengersUI: PassengersUI | null = null;
    private loadUI: LoadUI | null = null;
    private accessoriesUI: AccessoriesUI | null = null;
    private controlSurfacesUI: ControlSurfacesUI | null = null;
    private landingGearUI: LandingGearUI | null = null;
    private optimizationUI: OptimizationUI | null = null;
    private reinforcementsUI: ReinforcementsUI | null = null;
    private stabilizersUI: StabilizersUI | null = null;
    private initialized: boolean = false;
    private wasmModule: WasmModule | null = null;

    /**
     * Initialize the WASM application
     */
    async initialize(): Promise<void> {
        try {
            console.log('[WasmApp] Starting WASM initialization...');

            // Dynamically import the WASM module
            // This will be generated by wasm-pack: Test/pkg/flyingcircuswasm
            this.wasmModule = await this.loadWasmModule();

            if (!this.wasmModule) {
                console.warn('[WasmApp] WASM module not available, using fallback mode');
                return;
            }

            // Initialize WASM (this loads the .wasm binary)
            // The init function is the default export from wasm-pack
            const initWasm = this.wasmModule.default || this.wasmModule.init;
            if (typeof initWasm !== 'function') {
                throw new Error('WASM init function not found. Expected wasmModule.default to be a function.');
            }
            await initWasm();
            console.log('[WasmApp] WASM binary loaded');

            // Initialize localization with WASM backend
            localization.initializeWasm(this.wasmModule.Localization);
            console.log('[WasmApp] Localization initialized');

            // Register for language change events to reconstruct aircraft
            localization.onLocaleChange((locale) => this.onLanguageChange(locale));

            // Set locale from URL parameter or localStorage
            const urlParams = new URLSearchParams(window.location.search);
            const langParam = urlParams.get('lang');
            if (langParam) {
                localization.setLocale(langParam);
                console.log(`[WasmApp] Locale set from URL: ${langParam}`);
            }

            // Create aircraft bridge
            // Note: We already called initWasm() above, so we pass a no-op function
            this.bridge = new AircraftBridge();
            await this.bridge.initialize(
                async () => { /* Already initialized */ },
                this.wasmModule.AircraftWasm
            );
            console.log('[WasmApp] Aircraft bridge initialized');

            // Check for aircraft data in URL (for loading shared aircraft)
            let jsonParam = urlParams.get('json');
            //Debug: Always start with known aircraft.
            jsonParam = "AAEAjATAdA7MCwAhAhgZwJYGMAEj0AcAbZAOwFNgBAK4WgMFsfqcZBfZoHQAlACwHsSybAFl+AF34AnAEbIArtgBaYMNgAcABl75gAJGABcYACBa1GkzYAIVhw4B-h8FsAoex8-ngPAUNES0nKKKmpaOsAAwADq0QCSPnyCwmKSsgrKqhraurRmlACCUABmxQACAAmMAJBUAPwAAbSNzU32bEwWTp5mHL1RXvb9PZ2mjLa2HhPskXaj3p6zNZaDy6ssAKCe1BZsFuszTJMHSxwA4CdMpwf21JHUdPuMO-uvHk83B0A";
            if (jsonParam && this.bridge) {
                try {
                    const loadedBridge = await AircraftBridge.deserializeFromLZString(
                        jsonParam,
                        async () => { /* Already initialized */ },
                        this.wasmModule.AircraftWasm
                    );
                    this.bridge = loadedBridge;
                    console.log('[WasmApp] Loaded aircraft from URL');
                } catch (e) {
                    console.error('[WasmApp] Failed to load aircraft from URL:', e);
                }
            }

            // Create language selector
            this.languageSelector = new LanguageSelector('language_selector_container');
            console.log('[WasmApp] Language selector created');

            // Create Era UI component
            // Pass a bridge getter function so it always gets the current bridge
            this.eraUI = new EraUI(() => this.bridge, 'Era', () => {
                this.onStatsUpdate();
            });
            console.log('[WasmApp] Era UI created');

            // Create Cockpits UI component
            // Pass a bridge getter function so it always gets the current bridge
            this.cockpitsUI = new CockpitsUI(() => this.bridge, 'Cockpit', () => {
                this.onStatsUpdate();
            });
            console.log('[WasmApp] Cockpits UI created');

            // Create Propeller UI component
            this.propellerUI = new PropellerUI(() => this.bridge, 'Propeller', () => {
                this.onStatsUpdate();
            });
            console.log('[WasmApp] Propeller UI created');

            // Create Passengers UI component
            this.passengersUI = new PassengersUI(() => this.bridge, 'Passengers', () => {
                this.onStatsUpdate();
            });
            console.log('[WasmApp] Passengers UI created');

            // Create Load UI component (combines Fuel, Munitions, and Cargo)
            this.loadUI = new LoadUI(() => this.bridge, 'Load', () => {
                this.onStatsUpdate();
            });
            console.log('[WasmApp] Load UI created');

            // Create Accessories UI component
            this.accessoriesUI = new AccessoriesUI(() => this.bridge, 'Accessories', () => {
                this.onStatsUpdate();
            });
            console.log('[WasmApp] Accessories UI created');

            // Create ControlSurfaces UI component
            this.controlSurfacesUI = new ControlSurfacesUI(() => this.bridge, 'ControlSurfaces', () => {
                this.onStatsUpdate();
            });
            console.log('[WasmApp] ControlSurfaces UI created');

            // Create LandingGear UI component
            this.landingGearUI = new LandingGearUI(() => this.bridge, 'Landing_Gear', () => {
                this.onStatsUpdate();
            });
            console.log('[WasmApp] LandingGear UI created');

            // Create Optimization UI component
            this.optimizationUI = new OptimizationUI(() => this.bridge, 'Optimization', () => {
                this.onStatsUpdate();
            });
            console.log('[WasmApp] Optimization UI created');

            // Create Reinforcements UI component
            this.reinforcementsUI = new ReinforcementsUI(() => this.bridge, 'Reinforcements', () => {
                this.onStatsUpdate();
            });
            console.log('[WasmApp] Reinforcements UI created');

            // Create Stabilizers UI component
            this.stabilizersUI = new StabilizersUI(() => this.bridge, 'Stabilizers', () => {
                this.onStatsUpdate();
            });
            console.log('[WasmApp] Stabilizers UI created');

            this.initialized = true;
            console.log('[WasmApp] Initialization complete!');
        } catch (error) {
            console.error('[WasmApp] Failed to initialize WASM:', error);
            console.log('[WasmApp] Continuing with TypeScript-only mode');
        }
    }

    /**
     * Load the WASM module
     * Returns null if WASM is not available (not yet built)
     */
    private async loadWasmModule(): Promise<WasmModule | null> {
        try {
            // Try to import the WASM module
            // wasm-pack with --target bundler exports:
            // - default: initialization function
            // - named exports: classes and functions
            const wasmModule = await import('../pkg/flyingcircuswasm');

            // For bundler target, the default export is the init function
            // We need to wrap it to match our expected interface
            return {
                default: wasmModule.init_panic_hook,
                init: wasmModule.init_panic_hook, // The initialization function
                AircraftWasm: wasmModule.AircraftWasm,
                Localization: wasmModule.Localization
            };
        } catch (e) {
            console.warn('[WasmApp] WASM module not found (not yet built):', e);
            return null;
        }
    }

    /**
     * Called when language changes
     * Reconstructs the aircraft to regenerate UIBindings with new language
     */
    private async onLanguageChange(locale: string): Promise<void> {
        if (!this.bridge || !this.wasmModule) {
            console.warn('[WasmApp] Cannot reconstruct aircraft: bridge or module not initialized');
            return;
        }

        try {
            console.log(`[WasmApp] Language changed to ${locale}, reconstructing aircraft...`);

            // Serialize current aircraft state
            const serialized = this.bridge.serialize();
            console.log('[WasmApp] Aircraft serialized');

            // Locale has already been changed by LocalizationManager
            // Now deserialize to create a new aircraft with fresh UIBindings in the new language
            const newBridge = await AircraftBridge.deserialize(
                serialized,
                async () => { /* Already initialized */ },
                this.wasmModule.AircraftWasm
            );

            // Replace the bridge with the new one
            this.bridge = newBridge;
            console.log('[WasmApp] Aircraft reconstructed with new language');
            this.render(true);

            // Note: UI components will re-render automatically because they're registered
            // as locale change listeners in LocalizationManager
        } catch (error) {
            console.error('[WasmApp] Failed to reconstruct aircraft on language change:', error);
        }
    }

    private render(forceFull: boolean = false): void {
        this.eraUI.render(forceFull);
        this.cockpitsUI.render(forceFull);
        this.stabilizersUI.render(forceFull);
        this.controlSurfacesUI.render(forceFull);
        this.reinforcementsUI.render(forceFull);
        this.loadUI.render(forceFull);
        this.landingGearUI.render(forceFull);
        this.accessoriesUI.render(forceFull);
    }

    /**
     * Called when stats need to be updated
     */
    private onStatsUpdate(): void {
        if (!this.bridge) return;

        // Recalculate stats in Rust
        this.bridge.calculateStats();

        // Get derived stats
        const derivedStats = this.bridge.getDerivedStats();
        console.log('[WasmApp] Stats updated:', derivedStats);

        // TODO: Update stats display in UI
        // For now, just log to console
    }

    /**
     * Check if WASM is initialized
     */
    isInitialized(): boolean {
        return this.initialized;
    }

    /**
     * Get the aircraft bridge (if initialized)
     */
    getBridge(): AircraftBridge | null {
        return this.bridge;
    }
}

/**
 * Global WASM application instance
 */
export const wasmApp = new WasmApplication();
