var internal_id=0;function download(b,a,d){b=new Blob([b],{type:d});var c=document.createElement("a"),f=URL.createObjectURL(b);c.href=f;c.download=a;document.body.appendChild(c);c.click();setTimeout(function(){document.body.removeChild(c);window.URL.revokeObjectURL(f)},0)}
function copyStringToClipboard(b){var a=document.createElement("textarea");a.value=b;a.setAttribute("readonly","");a.style.position="absolute";a.style.left="-9999px";document.body.appendChild(a);a.select();document.execCommand("copy");document.body.removeChild(a)}function GenerateID(){internal_id++;return"internal_id_"+internal_id.toString()}
function CreateFlexSection(b){var a={div0:document.createElement("DIV"),div1:document.createElement("DIV"),div2:document.createElement("DIV")};a.div0.classList.add("flex-container-o");a.div1.classList.add("flex-container-i");a.div2.classList.add("flex-container-i");a.div0.appendChild(a.div1);a.div0.appendChild(a.div2);b.appendChild(a.div0);return a}function CreateTH(b,a){var d=document.createElement("TH");d.innerHTML=a;b.appendChild(d);return d}
function CreateTD(b,a){var d=document.createElement("TD");d.innerHTML=a;b.appendChild(d);return d}function CreateInput(b,a,d,c=!0){var f=document.createElement("SPAN"),e=document.createElement("LABEL");a.id=GenerateID();e.htmlFor=a.id;e.style.marginLeft="0.25em";e.style.marginRight="0.5em";e.textContent=b;a.setAttribute("type","number");a.min="0";a.step="1";a.valueAsNumber=0;f.appendChild(e);f.appendChild(a);d.appendChild(f);c&&d.appendChild(document.createElement("BR"))}
function FlexInput(b,a,d){var c=document.createElement("LABEL");a.id=GenerateID();c.htmlFor=a.id;c.style.marginLeft="0.25em";c.style.marginRight="0.5em";c.textContent=b;a.setAttribute("type","number");a.min="0";a.step="1";a.valueAsNumber=0;c.classList.add("flex-item");a.classList.add("flex-item");d.div1.appendChild(c);d.div2.appendChild(a)}
function FlexText(b,a,d){var c=document.createElement("LABEL");a.id=GenerateID();c.htmlFor=a.id;c.style.marginLeft="0.25em";c.style.marginRight="0.5em";c.textContent=b;a.setAttribute("type","text");a.value="Default";c.classList.add("flex-item");a.classList.add("flex-item");d.div1.appendChild(c);d.div2.appendChild(a)}
function FlexDisplay(b,a,d){var c=document.createElement("LABEL");a.id=GenerateID();c.htmlFor=a.id;c.style.marginLeft="0.25em";c.style.marginRight="0.5em";c.textContent=b;c.classList.add("flex-item");a.classList.add("flex-item");d.div1.appendChild(c);d.div2.appendChild(a)}
function FlexSelect(b,a,d){var c=document.createElement("LABEL");a.id=GenerateID();c.htmlFor=a.id;c.style.marginLeft="0.25em";c.style.marginRight="0.5em";c.textContent=b;c.classList.add("flex-item");a.classList.add("flex-item");d.div1.appendChild(c);d.div2.appendChild(a)}
function CreateCheckbox(b,a,d,c=!0){var f=document.createElement("SPAN"),e=document.createElement("LABEL");a.id=GenerateID();e.htmlFor=a.id;e.style.marginLeft="0.25em";e.style.marginRight="0.5em";e.textContent=b;a.setAttribute("type","checkbox");f.appendChild(e);f.appendChild(a);d.appendChild(f);c&&d.appendChild(document.createElement("BR"))}
function CreateSelect(b,a,d,c=!0){var f=document.createElement("SPAN"),e=document.createElement("LABEL");a.id=GenerateID();e.htmlFor=a.id;e.style.marginLeft="0.25em";e.style.marginRight="0.5em";e.textContent=b;f.appendChild(e);f.appendChild(a);d.appendChild(f);c&&d.appendChild(document.createElement("BR"))}
function CreateText(b,a,d,c=!0){var f=document.createElement("SPAN"),e=document.createElement("LABEL");a.id=GenerateID();e.htmlFor=a.id;e.style.marginLeft="0.25em";e.style.marginRight="0.5em";e.textContent=b;a.setAttribute("type","text");a.value="Default";f.appendChild(e);f.appendChild(a);d.appendChild(f);c&&d.appendChild(document.createElement("BR"))}
function CreateButton(b,a,d,c=!0){var f=document.createElement("SPAN"),e=document.createElement("LABEL");a.hidden=!0;a.id=GenerateID();a.textContent=b;e.htmlFor=a.id;e.style.marginLeft="0.25em";e.style.marginRight="0.5em";e.textContent=b;e.classList.add("lbl_action");e.classList.add("btn_th");f.appendChild(e);f.appendChild(a);d.appendChild(f);c&&(d.appendChild(document.createElement("BR")),d.appendChild(document.createElement("BR")))}
function FlexCheckbox(b,a,d){var c=document.createElement("LABEL");a.id=GenerateID();c.htmlFor=a.id;c.id=GenerateID();c.style.marginLeft="0.25em";c.style.marginRight="0.5em";c.textContent=b;a.setAttribute("type","checkbox");c.classList.add("flex-item");a.classList.add("flex-item");d.div1.appendChild(c);b=document.createElement("LABEL");var f=document.createElement("SPAN");f.appendChild(b);f.appendChild(a);d.div2.appendChild(f);return c}
function FlexLabel(b,a){var d=document.createElement("LABEL");d.style.marginLeft="0.25em";d.style.marginRight="0.5em";d.textContent=b;d.classList.add("flex-item");a.appendChild(d);return d}
function FlexLabels(b,a,d){var c=document.createElement("LABEL");c.style.marginLeft="0.25em";c.style.marginRight="0.5em";c.textContent=b;c.classList.add("flex-item");d.div1.appendChild(c);b=document.createElement("LABEL");b.style.marginLeft="0.25em";b.style.marginRight="0.5em";b.textContent=a;b.classList.add("flex-item");d.div2.appendChild(b);return[c,b]}
function FlexSpace(b){var a=document.createElement("LABEL");a.textContent=" ";a.classList.add("flex-item");b.div1.appendChild(a);a=document.createElement("LABEL");a.textContent=" ";a.classList.add("flex-item");b.div2.appendChild(a)}function insertRow(b){var a=document.createElement("TR");b.append(a);return a}function insertCell(b){var a=document.createElement("TD");b.append(a);return a}
function BlinkBad(b){b.classList.toggle("changed_b",!1);b.classList.toggle("changed_g",!1);b.classList.toggle("changed_n",!1);b.offsetHeight;b.classList.toggle("changed_b")}function BlinkGood(b){b.classList.toggle("changed_b",!1);b.classList.toggle("changed_g",!1);b.classList.toggle("changed_n",!1);b.offsetHeight;b.classList.toggle("changed_g")}
function BlinkNeutral(b){b.classList.toggle("changed_b",!1);b.classList.toggle("changed_g",!1);b.classList.toggle("changed_n",!1);b.offsetHeight;b.classList.toggle("changed_n")}function BlinkNone(b){b.classList.toggle("changed_b",!1);b.classList.toggle("changed_g",!1);b.classList.toggle("changed_n",!1)}
function BlinkIfChanged(b,a,d=null){if(enable_anim)if(b.textContent!=a)if(null==d)BlinkNeutral(b);else{var c=parseInt(b.textContent)<parseInt(a);d&&c||!d&&!c?BlinkGood(b):BlinkBad(b)}else BlinkNone(b);b.textContent=a}function _arrayBufferToString(b){var a="";b=new Uint8Array(b);for(var d=b.byteLength,c=0;c<d;c++)a+=String.fromCharCode(b[c]);return a}function _stringToArrayBuffer(b){var a=new Uint8Array(b.length);for(let d=0;d<b.length;d++)a[d]=b.charCodeAt(d);return a.buffer}
const loadJSON=(b,a)=>{let d=new XMLHttpRequest;d.overrideMimeType("application/json");d.open("GET",b,!0);d.onreadystatechange=()=>{4===d.readyState&&200===d.status&&a(d.responseText)};d.send(null)},init=()=>{var b=(new URLSearchParams(location.search)).get("lang"),a=["/PlaneBuilder/strings.json","/PlaneBuilder/weapons.json"].map(d=>fetch(d));Promise.all(a).then(d=>Promise.all(d.map(c=>c.json()))).then(d=>{var c=d[1];local=new Localization(d[0]);b?local.SetLanguages(b):window.localStorage.language&&
local.SetLanguages(window.localStorage.language);d=document.getElementById("table_weap");let f=[];for(var e of c.weapons)f.push({name:e.name,abrv:e.abrv,era:e.era,size:e.size,damage:e.damage,hits:e.hits,ammo:e.ammo,ap:e.ap,jam:e.jam,reload:e.reload,rapid:e.rapid,synched:e.synched,shells:e.shells,can_action:e.can_action,can_projectile:e.can_projectile,deflection:e.deflection,cost:e.cost,mass:e.mass,drag:e.drag,warn:e.warning});var l=h=>{switch(h){case "Pioneer":return 0;case "WWI":return 1;case "Roaring 20s":return 2;
case "Coming Storm":return 3;case "WWII":return 4;case "Last Hurrah":return 5;case "Himmilgard":return 6}};f=f.sort((h,k)=>{var m=(n,p)=>n<p?-1:p<n?1:0;return h.size!=k.size?m(h.size,k.size):h.era!=k.era?m(l(h.era),l(k.era)):h.damage!=k.damage?m(h.damage,k.damage):m(h.name,k.name)});for(var g of f){c=d.insertRow();CreateTD(c,g.name);CreateTD(c,g.abrv);CreateTD(c,g.era);CreateTD(c,g.cost);CreateTD(c,g.mass);CreateTD(c,g.drag);CreateTD(c,g.hits);CreateTD(c,g.damage);CreateTD(c,g.ap);CreateTD(c,g.ammo);
CreateTD(c,g.reload);CreateTD(c,g.jam);switch(g.size){case 1:CreateTD(c,"Tiny");break;case 2:CreateTD(c,"Light");break;case 4:CreateTD(c,"Medium");break;case 8:CreateTD(c,"Heavy");break;case 16:CreateTD(c,"Artillery")}e="";g.rapid&&(e+="Rapid-Fire ");g.Manual&&(e+="Manual ");g.shells&&(e+="Shell-Firing ");g.synched||(e+="Open-Bolt ");CreateTD(c,e);e=g.deflection;0>e?CreateTD(c,"Yes, "+e):CreateTD(c,"No");g.warn?CreateTD(c,lu(g.warn)):CreateTD(c,"")}g=d.insertRow();CreateTH(g,"Name");CreateTH(g,"Abbreviation");
CreateTH(g,"Era");CreateTH(g,"Cost");CreateTH(g,"Mass");CreateTH(g,"Drag");CreateTH(g,"Hits");CreateTH(g,"Damage");CreateTH(g,"AP");CreateTH(g,"Ammo");CreateTH(g,"Reload");CreateTH(g,"Jam");CreateTH(g,"Size");CreateTH(g,"Tags");CreateTH(g,"Awkward");CreateTH(g,"Notes")})};window.onload=init;var enable_anim=!1,local;
class StringFmt{static IsNullOrWhiteSpace(b){try{return null==b||"undefined"==b?!0:1>b.toString().replace(/\s/g,"").length}catch(a){return console.log(a),!1}}static Join(b,...a){try{let d=a[0];if(Array.isArray(d)||d instanceof Array){let c=StringFmt.Empty;for(a=0;a<d.length;a++){let f=d[a];c=a<d.length-1?c+(f+b):c+f}return c}if("object"===typeof d){let c=StringFmt.Empty;Object.keys(d).forEach(f=>{c+=d[f]+b});return c=c.slice(0,c.length-b.length)}return StringFmt.join(b,...a)}catch(d){return console.log(d),
StringFmt.Empty}}static Format(b,...a){try{return b.match(StringFmt.regexNumber)?StringFmt.format(StringFmt.regexNumber,b,a):b.match(StringFmt.regexObject)?StringFmt.format(StringFmt.regexObject,b,a,!0):b}catch(d){return console.log(d),StringFmt.Empty}}static format(b,a,d,c=!1){return a.replace(b,function(f,e){let l=f.split(":");1<l.length&&(e=l[0].replace("{",""),f=l[1].replace("}",""));e=c?d[0][e]:d[e];if(null==e||void 0==e||f.match(/{\d+}/))return e;e=StringFmt.parsePattern(f,e);return"undefined"!=
typeof e&&null!=e?e:StringFmt.Empty})}static parsePattern(b,a){switch(b){case "L":return a.toLocaleLowerCase();case "U":return a.toLocaleUpperCase();case "d":if("string"===typeof a)return StringFmt.getDisplayDateFromString(a);if(a instanceof Date)return StringFmt.Format("{0:00}.{1:00}.{2:0000}",a.getDate(),a.getMonth(),a.getFullYear());break;case "s":if("string"===typeof a)return StringFmt.getSortableDateFromString(a);if(a instanceof Date)return StringFmt.Format("{0:0000}-{1:00}-{2:00}",a.getFullYear(),
a.getMonth(),a.getDate());break;case "n":"string"!==typeof a&&(a=a.toString());var d=a.replace(/,/g,".");if(isNaN(parseFloat(d))||3>=d.length)break;b=a=d.split(/[^0-9]+/g);1<a.length&&(b=[StringFmt.join("",...a.splice(0,a.length-1)),a[a.length-1]]);let c=b[0];d=c.length%3;a=0<d?c.substring(0,d):StringFmt.Empty;d=c.substring(d).match(/.{3}/g);a=a+"."+StringFmt.Join(".",d);return a+(1<b.length?","+b[1]:"");case "x":return this.decimalToHexString(a);case "X":return this.decimalToHexString(a,!0)}return"number"!==
typeof a&&isNaN(a)||isNaN(+b)||StringFmt.IsNullOrWhiteSpace(a)?a:StringFmt.formatNumber(a,b)}static decimalToHexString(b,a=!1){b=parseFloat(b).toString(16);return a?b.toLocaleUpperCase():b}static getDisplayDateFromString(b){var a=b.split("-");if(1>=a.length)return b;b=a[a.length-1];let d=a[a.length-2];a=a[a.length-3];b=b.split("T")[0];b=b.split(" ")[0];return`${b}.${d}.${a}`}static getSortableDateFromString(b){var a=b.replace(",","").split(".");if(1>=a.length)return b;let d=a[a.length-1].split(" ");
b=StringFmt.Empty;1<d.length&&(b=d[d.length-1]);a=`${a[a.length-1].split(" ")[0]}-${a[a.length-2]}-${a[a.length-3]}`;return!StringFmt.IsNullOrWhiteSpace(b)&&1<b.length?a+`T${b}`:a+"T00:00:00"}static formatNumber(b,a){a=a.length;b=b.toString();return a<=b.length?b:Array(a-b.length+1).join("0")+b}static join(b,...a){let d=StringFmt.Empty;for(let c=0;c<a.length;c++)if(!("string"==typeof a[c]&&StringFmt.IsNullOrWhiteSpace(a[c])||"number"!=typeof a[c]&&"string"!=typeof a[c])){d+=""+a[c];for(let f=c+1;f<
a.length;f++)if(!StringFmt.IsNullOrWhiteSpace(a[f])){d+=b;c=f-1;break}}return d}}StringFmt.regexNumber=/{(\d+(:\w*)?)}/g;StringFmt.regexObject=/{(\w+(:\w*)?)}/g;StringFmt.Empty="";
class StringBuilder{constructor(b){this.Values=[];StringFmt.IsNullOrWhiteSpace(b)||(this.Values=Array(b))}ToString(){return this.Values.join("")}Append(b){this.Values.push(b)}AppendLine(b){this.Values.push("\r\n"+b)}AppendFormat(b,...a){this.Values.push(StringFmt.Format(b,...a))}AppendLineFormat(b,...a){this.Values.push("\r\n"+StringFmt.Format(b,...a))}Clear(){this.Values=[]}}
class Localization{constructor(b){this.lang="en";this.languages=b}GetLanguages(){var b=[];for(let a of this.languages.languages)b.push(a);return b}SetLanguages(b){this.languages[b]&&(this.lang=b)}e(b){if(this.languages[this.lang][b])return this.languages[this.lang][b];if(this.languages.en[b])return this.languages.en[b];console.error("Failed to find "+b);return"!"+b+"!"}}function lu(b,...a){return StringFmt.Format(local.e(b),...a)};
